import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// One card from a bundled catalog: a real printed card, with the attributes
/// the deck builder needs already filled in.
///
/// Catalogs are generated by `tool/build_catalog.dart`. Entries use short keys
/// to keep the asset small; [_aliases] maps them back to the attribute names
/// the game definitions use, and any key not listed passes through unchanged so
/// another game can add attributes of its own.
class CatalogCard {
  const CatalogCard({
    required this.name,
    required this.lowerName,
    required this.attributes,
    required this.searchText,
  });

  final String name;
  final Map<String, String> attributes;

  /// The name, lowercased once so searching stays cheap.
  final String lowerName;

  /// Lowercased name and card number, so a search matches either.
  final String searchText;

  String? get cardNo => attributes['cardNo'];

  static const _aliases = <String, String>{
    'g': 'grade',
    't': 'cardType',
    'tr': 'trigger',
    'na': 'nation',
    'c': 'clan',
    'p': 'power',
    's': 'shield',
    'no': 'cardNo',
    'e': 'effect',
    'i': 'imageUrl',
    'sr': 'series',
  };

  /// [imageBase] is the shared prefix the catalog strips from image URLs to
  /// keep the asset small; it is put back here so the rest of the app only
  /// ever sees a complete URL.
  static CatalogCard fromJson(
    Map<String, dynamic> json, {
    String imageBase = '',
  }) {
    final name = json['n'] as String? ?? '';
    final attributes = <String, String>{};
    for (final entry in json.entries) {
      if (entry.key == 'n' || entry.value == null) continue;
      final key = _aliases[entry.key] ?? entry.key;
      final value = '${entry.value}';
      attributes[key] = key == 'imageUrl' ? '$imageBase$value' : value;
    }
    final lowerName = name.toLowerCase();
    final cardNo = (attributes['cardNo'] ?? '').toLowerCase();
    return CatalogCard(
      name: name,
      lowerName: lowerName,
      attributes: attributes,
      searchText: cardNo.isEmpty ? lowerName : '$lowerName $cardNo',
    );
  }
}

/// Parsed off the UI thread, because the Vanguard catalog runs to megabytes.
List<CatalogCard> parseCatalog(String raw) {
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final imageBase = json['imageBase'] as String? ?? '';
  return (json['cards'] as List)
      .whereType<Map<String, dynamic>>()
      .map((card) => CatalogCard.fromJson(card, imageBase: imageBase))
      .toList(growable: false);
}

/// Loads and searches the bundled card catalogs.
class CardCatalog {
  final _cache = <String, List<CatalogCard>>{};
  final _loading = <String, Future<List<CatalogCard>>>{};

  bool isLoaded(String assetPath) => _cache.containsKey(assetPath);

  int countOf(String assetPath) => _cache[assetPath]?.length ?? 0;

  /// Installs a catalog directly, so tests do not have to read and parse the
  /// real multi-megabyte asset.
  @visibleForTesting
  void seed(String assetPath, List<CatalogCard> cards) {
    _cache[assetPath] = cards;
  }

  /// Loads a catalog once and keeps it. Concurrent callers share one load.
  Future<List<CatalogCard>> load(String assetPath) {
    final cached = _cache[assetPath];
    if (cached != null) return Future.value(cached);

    return _loading[assetPath] ??= () async {
      try {
        final raw = await rootBundle.loadString(assetPath);
        final cards = await compute(parseCatalog, raw);
        _cache[assetPath] = cards;
        return cards;
      } on Exception {
        // A missing or malformed catalog must not take the app down. The
        // screens fall back to entering cards by hand.
        _cache[assetPath] = const [];
        return const <CatalogCard>[];
      } finally {
        _loading.remove(assetPath);
      }
    }();
  }

  /// Cards matching [query], best matches first.
  ///
  /// Ranking runs exact name, then name prefix, then a word inside the name,
  /// then anything else containing the query, which is what matches a card
  /// number. An empty query with a filter set browses that filter's cards.
  static List<CatalogCard> search(
    List<CatalogCard> cards,
    String query, {
    Map<String, String> filters = const {},
    int limit = 60,
  }) {
    final needle = query.trim().toLowerCase();
    final active = {
      for (final filter in filters.entries)
        if (filter.value.isNotEmpty) filter.key: filter.value,
    };
    if (needle.isEmpty && active.isEmpty) return const [];

    final ranked = <_Ranked>[];
    for (final card in cards) {
      var keep = true;
      for (final filter in active.entries) {
        if (card.attributes[filter.key] != filter.value) {
          keep = false;
          break;
        }
      }
      if (!keep) continue;

      if (needle.isEmpty) {
        ranked.add(_Ranked(3, card));
        continue;
      }

      final name = card.lowerName;
      int? rank;
      if (name == needle) {
        rank = 0;
      } else if (name.startsWith(needle)) {
        rank = 1;
      } else if (name.contains(' $needle')) {
        rank = 2;
      } else if (card.searchText.contains(needle)) {
        rank = 3;
      }
      if (rank != null) ranked.add(_Ranked(rank, card));
    }

    ranked.sort((a, b) {
      final byRank = a.rank.compareTo(b.rank);
      if (byRank != 0) return byRank;
      return a.card.lowerName.compareTo(b.card.lowerName);
    });

    return [for (final entry in ranked.take(limit)) entry.card];
  }
}

class _Ranked {
  const _Ranked(this.rank, this.card);

  final int rank;
  final CatalogCard card;
}
